services:
  - type: web
    name: rogue-nomad-bot
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8279300523:AAGC71G8Dd9QmmF2Yhn6MUSTKq7i-4q6p7w
      - key: ADMIN_ID
        value: 1875307475
      - key: DATABASE_URL
        value: rogue_nomad.db
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /health
    autoDeploy: true
