services:
  - type: web
    name: rogue-nomad-bot
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8651086980:AAFe43rg62NOceSHi-kdb5gbEK5QRqqr09E
      - key: ADMIN_ID
        value: 1875307475
      - key: CHANNEL_ID
        value: -1003861121732
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
